### ISSUE TITLE
KeyDB 6.3.4

### ISSUE THREAD

**Issue by aleksasiriski** [voidsolutionsorg/keydb-chart#1]
Update KeyDB version to use 6.3.4

**Comment by lazarivkovic** [comment]
`  imageRepository: docker.io/eqalpha/keydb `
`  imageTag: x86_64_v6.3.4 `

**Comment by aleksasiriski** [comment]
You have to change the version in the [chart.yaml](https://github.com/voidsolutionsorg/keydb-chart/blob/master/charts/keydb/Chart.yaml#L23)

**Comment by aleksasiriski** [comment]
Also [here](https://github.com/voidsolutionsorg/keydb-chart/blob/master/charts/keydb/values.yaml#L5)
